@startuml
title 案件処理
|依頼者（個人/藩国）|

start
:罰則への異議申し立て窓口スレッドへの書き込み;

|護民官受付担当者|
:受付完了の返信;
:案件作業用スレッドの作成;
:作業リーダー募集開始;

|護民官作業リーダー|
:案件作業用スレッド
へのエントリー;
:作業１：要調査項目ピックアップ
の作業者募集（2名）;

|護民官作業者|
:作業１へのエントリー;
:調査;
:調査結果報告;

|護民官作業リーダー|
:調査結果まとめ;
while (調査結果に不足がある)
:再調査依頼;
|護民官作業者|
:再調査;
:再調査結果報告;
endwhile

|護民官作業リーダー|
:調査項目のまとめ報告;

:作業２：案件の調査
の作業者募集（複数名）;

|護民官作業者|
:作業２へのエントリー;
:調査;
fork
:依頼者への聞き取り;
|依頼者（個人/藩国）|
:対応する;
fork again
|護民官作業者|
:関係者への聞き取り;
fork again
:詳細調査;
end fork
:調査結果報告;

|護民官作業リーダー|
:案件調査のまとめ;

:作業３：案件の救済判断
の作業者募集（2名）;

|護民官作業者|
:作業３へのエントリー;
:救済案の作成;
:救済案の報告;

|護民官作業リーダー|
:救済案のとりまとめ;
if (救済が難しいか) then (難しい場合)
:依頼者に取り下げをお願いする;
|依頼者（個人/藩国）|
:取り下げる;
stop

|護民官作業リーダー|
repeat
:救済案の作成;
:救済案について上位裁定依頼;
|上位裁定者|
:救済案チェック;
repeat while (問題がある) 

|護民官作業リーダー|
repeat
:救済案について芝村さんへの
相談文面作成;
:上位裁定者へ相談文面チェック依頼;
|上位裁定者|
:文案チェック;
repeat while (問題がある) 

|護民官作業リーダー|
:芝村さんへの報連相スレッドへの書き込み;
:DMにて連絡;

|芝村さん|
:相談内容について返答;

|護民官作業リーダー|
:回答のスレッドへの転記;

while (救済案に問題がある)
:救済案の再作成;
:救済案について上位裁定依頼;
|上位裁定者|
:救済案チェック;
|護民官作業リーダー|
:芝村さんへの報連相スレッドへの書き込み;
:DMにて連絡;
|芝村さん|
:相談内容について返答;
|護民官作業リーダー|
:回答のスレッドへの転記;
endwhile

|護民官作業リーダー|
:作業４：再裁定依頼（作業リーダー担当）
の開始をスレッドに書き込む;
repeat
:再裁定依頼文の作成;
:再裁定依頼文について上位裁定依頼;
|上位裁定者|
:再裁定依頼文チェック;
repeat while(問題がある)

|護民官作業リーダー|
:法官BBSの護民官申出受付ツリー
に再裁定依頼を投稿する;
:法官長（伯牙さん）にDMする;

fork
:依頼者に再裁定完了報告をする;
|依頼者（個人/藩国）|
:対応する;
fork again
|法官|
:対応する;
while (再裁定依頼に問題がある)
:作業リーダーに問題点を指摘する;
|護民官作業リーダー|
:再裁定依頼を取り下げる;
:再裁定依頼を再検討する;
repeat
:再裁定依頼文の作成;
:再裁定依頼文について上位裁定依頼;
|上位裁定者|
:再裁定依頼文チェック;
repeat while(問題がある)
:法官BBSの護民官申出受付ツリー
に再裁定依頼を投稿する;
:法官長（伯牙さん）にDMする;
endwhile
fork end
:再裁定結果を護民官に連絡する;

|護民官作業リーダー|
:作業５：;
stop
@enduml